apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appname.labels" . | indent 4 }}
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: mywebapp
    tier: frontend
  type: NodePort